version: '3.8'

services:
  app:
    build: .
    container_name: zibro_server_app
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=zibro_user
      - DATABASE_PASSWORD=your_strong_password
      - DATABASE_NAME=zibro_db

  db:
    image: postgres:15-alpine
    container_name: zibro_postgres_db
    environment:
      POSTGRES_DB: zibro_db
      POSTGRES_USER: zibro_user
      POSTGRES_PASSWORD: your_strong_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
